### ISSUE TITLE
TODO List for 26 July... or whenever I get the time next

### ISSUE THREAD

**Issue by gldraphael** [gldraphael/evlog#104]
- [x] Recreate migrations
- [x] Tidy up some code
- [x] Fix the docker setup
- [x] Get tests working
- [x] Get identity setup working
