### ISSUE TITLE
TODO for 9th August or whatever weekend I get the time next

### ISSUE THREAD

**Issue by gldraphael** [gldraphael/evlog#116]
- [ ] Work out the auth story for admins.
- [x] Revisit event registration -- they probably should end up in the users table too.
- [ ] Start documenting features, and plan for a v1 release by 10 Jan 2021 (the Sunday after new years 😁).

**Comment by gldraphael** [comment]
Stories here: https://miro.com/app/board/o9J_knu59m8=/

**Comment by gldraphael** [comment]
Will work on improving the admin panel for v0.2 or v0.3.
It's also too early to work on v1. Might wait till v0.5 or v0.6, so I get enough time to experiment a bit more.
